//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRJ_DB_REGION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departements()
        {
            this.Villes = new HashSet<Villes>();
        }
    
        public int idDepartement { get; set; }
        public string region_code { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public int idRegion { get; set; }
    
        public virtual Regions Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Villes> Villes { get; set; }
    }
}
