//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRJ_DB_REGION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villes
    {
        public int idVille { get; set; }
        public string department_code { get; set; }
        public string insee_code { get; set; }
        public string zip_code { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public Nullable<decimal> gps_lat { get; set; }
        public Nullable<decimal> gps_lng { get; set; }
        public int idDepartement { get; set; }
    
        public virtual Departements Departements { get; set; }
    }
}
